### ISSUE TITLE
Errore compilazione nextion

### ISSUE THREAD

**Issue by giangi007** [ThomasAndreini/Jarvis#4]
Ciao mi da il seguente errore quando compilo: Error: Invalid Page ID:page pageparent.val( Double click to jump to code); l'ho compilato con l'ultima versione di nextion editor. Mi puoi aiutare

**Comment by ThomasAndreini** [comment]
Ciao, uso la 0.32 e non sono ancora passato alla nuova proprio perche' dovrei riadattare il codice e ora non ho tempo.

Puoi scaricare la 0.32 da [questo link](http://7i7i8x.com1.z0.glb.clouddn.com/nextion-setup-v032.exe)
